# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7fadcf172d36e03db7a0990b00b9fa5b552ce5c923d73fd8b91532ae1c3fa607099bb697b61e5acbc1e9d3daf7173cbc7aed53fb84e1d670b9fcb50a511df2c

test:
  secret_key_base: d7866fee3b11af6733f90e735950fbdf38236709ce93475ced68bd143f96519a58e9e616277b8e02f4912e9ba14d6d88704038cd299aa852fba7ea3bec93b637

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
